config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :pins do 
  	get 'profile', action: 'profile'
  end

  root "pins#index"
  end



#   CarrierWaveExample::Application.routes.draw do
#    resources :resumes, only: [:index, :new, :create, :destroy]
#    root "resumes#index"
# end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user

  has_attached_file :image, :styles => { :medium => "300x300>"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	has_attached_file :resume,
                :storage => :s3,
                :s3_credentials => Proc.new{|a| a.instance.s3_credentials },
                :region => 'us-west-1',
                :s3 => { :region => 'us-east-1' },
                :s3_path_url => "us-east-1"
                # :url => ":s3_us_url"

  def s3_credentials
    {:bucket => "fairefortune", :access_key_id => "AKIAI44RTN66PGIVZ4LQ", :secret_access_key => "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"}
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :pins

end

#each pin that is created should have a user assigned to it,  so  we need  to add association between the two 
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path resource
  	"/pins/#{current_user.id}/profile"
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
before_action :find_pin  , only:[:show, :edit, :update, :destroy]

def index 
	@pins = Pin.all.order("created_at DESC")
end

def show 
	@pin = Pin.find params[:id]
end

def profile

end

def new
	@pin = Pin.new
end 

def create 
	@pin = Pin.new(pin_params)

	if @pin.save
		redirect_to @pin, notice: "Successfully created new Pin"

	else
		render 'new'
	end 

end

def edit
end 

def update
	if @pin.update(pin_params)
		redirect_to @pin, notice: "Pin was Successfully posted"
	else
		render 'edit'
	end	
end

def destroy
	@pin.destroy
	redirect_to root_path
end  


private

def pin_params
	params.require(:pin).permit(:title,:description,:image,:resume,:skill,:location)
end 

def find_pin
	@pin = Pin.find(params[:id])
end



end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

	protected

	def after_sign_in_path_for resource
		"/pins/#{current_user.id}/profile"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Faire Fortune</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
	<div class="container">
		<div class="navbar-brand">
			<%= link_to "Faire Fortune", root_path %>
		</div>	
			<div class="sider">
				<% if user_signed_in? %>
					<ul class="nav navbar-nav navbar-right">
						<li><%= link_to 'New status', new_pin_path, :class => 'navbar-link'%></li>
						<li><%= link_to 'account', edit_user_registration_path, :class => 'navbar-link'%></li>
						<li><%= link_to 'Sign out', destroy_user_session_path, method: :delete, :class => 'navbar-link'%>
						</li>
					</ul>
				<% else %>
					<ul class="nav navbar-nav navbar-right">
						<li><%= link_to 'Sign Up', new_user_registration_path, :class => 'navbar-link'%></li>
						<li><%= link_to 'Sign In', new_user_session_path, :class => 'navbar-link'%></li>
				<% end %>
		            </ul>
		    </div>
		
	</div>
</nav>

<div class="container">

<% flash.each do |name, msg| %>
	<%= content_tag :div, msg, class: "alert alert-info" %>
<% end %>
<%= yield %>

</div>
</body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: {multipart: true}) do |f| %> <%#this is for  the image uploading%>
	<% if @pin.errors.any? %>
		<div id="error_explanation">
			<h2> <%= pluralize(@pin.errors.count, "error") %>
			This  pin shall be prevented from saving </h2>
			<ul>
				<% @pin.errors.full_messages.each do |msg| %>
			 		<li><%= msg %></li>
				<% end %> 
			</ul>
		</div>
	<% end %>
	
	<div class="form-group" >
		<%= f.input :image, input_html: {class: 'form-control'} %>
		<%= f.input :resume, input_html: {class: 'form-control'} %>
		<%= f.input :title, input_html: {class: 'form-control'} %>
		<%= f.input :description, input_html: {class: 'form-control'} %>
		<%= f.input :skills, input_html: {class: 'form-contrl'} %>
		<%= f.select :location, options_for_select([ "Bangalore", "Chennai" ], "Bangalore"), {}, { class: 'form-control' } %><br>
		<%= f.button :submit, class: "btn btn-primary" %>
		
    </div>
	<% end %>

app/views/pins/edit.html.erb
p<div class="col-md-6 col-md-offset-3">
<h1>edit</h1>
<%= image_tag @pin.image.url(:medium) %>
<%= render 'form' %>
<%= link_to "cancel", pin_path %>
</div>

app/views/pins/index.html.erb
<!-- <div id="masonry-container" class="transitions-enabled centered clearfix masonry">
	<div class="row">
	<% @pins.each do |pin| %>
		<div class="box col3 panel panel-default">
			<%= image_tag pin.image.url(:medium) %><br>
			<div class="panel-body">	
				<%= link_to pin.title , pin %>
			</div>
			<% end %>
		</div>
	</div>
</div>
 -->
 <div class="container">
  <br>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="/assets/dev1.jpg" alt="Chania" width="100%" height="100%">
      </div>

      <div class="item">
        <img src="/assets/dev2.jpg" alt="Chania" width="100%" height="100%">
      </div>
    
      <div class="item">
        <img src="/assets/dev3.jpg" alt="Flower" width="100%" height="100%">
      </div>
<!-- 
      <div class="item">
        <img src="/assets/dev1.jpg" alt="Flower" width="460" height="345">
      </div> -->
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

</body>
</html>

app/views/pins/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<h1>status update </h1>

	<%= render "form" %>

	<%= link_to "Back", root_path %>
</div>

app/views/pins/profile.html.erb
<div ng-app="fortuneGraph" ng-controller="graphController">
<div class="col-md-4">
  <highchart class="col-md-12" id="chart1" config="scatter"></highchart>
</div>
<div class="col-md-4">
  <highchart class="col-md-12" id="chart1" config="bar"></highchart>
</div>
<div class="col-md-4">
  <highchart class="col-md-12" id="chart1" config="pie"></highchart>
</div>
<!-- <div class="col-md-3">
  <highchart class="col-md-12" id="chart1" config="stackedColumns"></highchart>
</div> -->
<%= current_user %>
</div>

app/views/pins/show.html.erb
<div class="row">

	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-default">
			<p><%= image_tag @pin.image.url(:medium) %></p>
			<h1> 
				<%= @pin.title %>  
			</h1>
			<p> 
			<%= @pin.description %>
 			</p>
 			<p> 
			<%= @pin.skills %>
 			</p>
 			<p> 
			<%= @pin.location %>
 			</p>
 			<%= @pin.user %>
		<%= link_to "Back", root_path %>
		<%= link_to "Edit", edit_pin_path %> 
		<%= link_to "delete", pin_path, method: :delete, data: { confirm: "are you sure ?"} %>
		</div>
	</div>
</div>